apiVersion : apps/v1
kind: Deployment
metadata:
  name: website 
spec:
  replicas: 10
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website 
    spec:
      containers:
        - name: website 
          image: acrpod.azurecr.io/website
          ports:
          - containerPort: 80
